// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bug: string;
  dark: string;
  dragon: string;
  electric: string;
  fairy: string;
  fighting: string;
  fire: string;
  ghost: string;
  gosth: string;
  grass: string;
  ground: string;
  ice: string;
  label: string;
  labelWrap: string;
  normal: string;
  poison: string;
  pokemonAbilities: string;
  pokemonAbilitiesText: string;
  pokemonCard: string;
  pokemonCircle: string;
  pokemonDefAndAttack: string;
  pokemonDefAndAttackItem: string;
  pokemonExp: string;
  pokemonGenAndCircle: string;
  pokemonGeneration: string;
  pokemonHealth: string;
  pokemonHealthAndExp: string;
  pokemonImage: string;
  pokemonInfo: string;
  pokemonName: string;
  pokemonNums: string;
  pokemonPic: string;
  pokemonProgressBar: string;
  pokemonProgressBarReady: string;
  pokemonState: string;
  pokemonStateText: string;
  pokemonStats: string;
  psychic: string;
  rock: string;
  root: string;
  stile: string;
  water: string;
}
export const cssExports: CssExports;
export default cssExports;
