// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  contentWrap: string;
  homePageContent: string;
  homePageContentParallax: string;
  homePageContentText: string;
  root: string;
}
export const cssExports: CssExports;
export default cssExports;
