// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cardList: string;
  cardListItem: string;
  search: string;
  title: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
