// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cardWrapper: string;
  root: string;
  title: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
